name: "Post-Op Action"
description: "Logs end time and duration"
runs:
  using: "composite"
  steps:
    - name: Capture End Time and Duration
      run: |
        END_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        echo "END_TIME=$END_TIME"
        if [[ -n "$START_TIME" ]]; then
          echo "Start Time: $START_TIME"
          echo "End Time: $END_TIME"
        fi
      shell: bash
