name: "Pre-Op Action"
description: "Collects metadata and saves as JSON"
inputs:
  debug:
    description: 'Enable debug mode'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set Start Time
      run: echo "START_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
      shell: bash

    - name: Collect Inputs and Save JSON
      run: |
        mkdir -p metadata
        START_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        DEBUG_MODE="${{ inputs.debug }}"
        
        # Collect input parameters
        echo "{" > metadata/pre_op.json
        echo "  \"start_time\": \"$START_TIME\"," >> metadata/pre_op.json
        echo "  \"debug_mode\": \"$DEBUG_MODE\"," >> metadata/pre_op.json
        echo "  \"inputs\": {" >> metadata/pre_op.json

        input_lines=""
        for var in $(env); do
          if [[ $var == INPUT_* ]]; then
            key=$(echo $var | cut -d= -f1 | sed 's/^INPUT_//' | tr '[:upper:]' '[:lower:]')
            value=$(echo $var | cut -d= -f2-)
            input_lines+="    \"$key\": \"$value\",\n"
          fi
        done

        # Remove last comma
        input_lines=$(echo -e "$input_lines" | sed '$s/,$//')

        echo -e "$input_lines" >> metadata/pre_op.json
        echo "  }" >> metadata/pre_op.json
        echo "}" >> metadata/pre_op.json
      shell: bash
