name: "Pre-Op Action"
description: "Collects all INPUT_* env vars dynamically"
runs:
  using: "composite"
  steps:
    - name: Generate Pre-Op JSON Dynamically
      run: |
        mkdir -p metadata
        START_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

        echo "{" > metadata/pre_op.json
        echo "  \"start_time\": \"$START_TIME\"," >> metadata/pre_op.json
        echo "  \"inputs\": {" >> metadata/pre_op.json

        input_lines=""
        for var in $(env); do
          if [[ $var == INPUT_* ]]; then
            key=$(echo $var | cut -d= -f1 | sed 's/^INPUT_//' | tr '[:upper:]' '[:lower:]')
            value=$(echo $var | cut -d= -f2-)
            input_lines+="    \"$key\": \"$value\",\n"
          fi
        done

        # Trim trailing comma
        input_lines=$(echo -e "$input_lines" | sed '$s/,$//')

        echo -e "$input_lines" >> metadata/pre_op.json
        echo "  }" >> metadata/pre_op.json
        echo "}" >> metadata/pre_op.json

        echo "START_TIME=$START_TIME" >> $GITHUB_ENV
      shell: bash
